### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by alabeduarte** [thaisfreitas/guarda-nota#1]
Hi @thaisfreitas 

Have you considered adding a CI to this repo, like [travis-ci](https://travis-ci.org)?

Cheers

**Comment by thaisfreitas** [comment]
Hey man,
Yes, I do!
I took a fast look at it travis-ci and its looks so good. 
Do you think I can add it there even I have a basic and simple code for now? As I didn't take in a deep investigation in travis, I'm not sure if it is the time to already add it there. What do you think about it?

Thanks for your suggestions :D

**Comment by alabeduarte** [comment]
I think the sooner the better!

**Comment by thaisfreitas** [comment]
I see.. So, I will work on that as soon as possible. I will let u know when i close this issue @alabeduarte ;)

**Comment by thaisfreitas** [comment]
Done! https://travis-ci.org/thaisfreitas/guarda-nota
Let me know if you don't have access to see this.

And feel free to send more suggestions and improvements.
